// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUYKKCb9-tzNWH6JFq-hCE4BUCIDtGXiI',
    appId: '1:670545276013:web:6670df127df5fa16176364',
    messagingSenderId: '670545276013',
    projectId: 'chat-app-f4037',
    authDomain: 'chat-app-f4037.firebaseapp.com',
    storageBucket: 'chat-app-f4037.appspot.com',
    measurementId: 'G-L51CEV29JE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN2NRQRI33TpZvZrPI8c3HsjDyxT9FFDg',
    appId: '1:670545276013:android:49214ee6d36f1cb5176364',
    messagingSenderId: '670545276013',
    projectId: 'chat-app-f4037',
    storageBucket: 'chat-app-f4037.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB319HMYxBSln-VaBxeBLpd0ER_qE0SOBE',
    appId: '1:670545276013:ios:1a4a84ed84129534176364',
    messagingSenderId: '670545276013',
    projectId: 'chat-app-f4037',
    storageBucket: 'chat-app-f4037.appspot.com',
    iosClientId: '670545276013-lu77l2kbe74rq6gb9d7agi5eqoj72sn5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB319HMYxBSln-VaBxeBLpd0ER_qE0SOBE',
    appId: '1:670545276013:ios:1a4a84ed84129534176364',
    messagingSenderId: '670545276013',
    projectId: 'chat-app-f4037',
    storageBucket: 'chat-app-f4037.appspot.com',
    iosClientId: '670545276013-lu77l2kbe74rq6gb9d7agi5eqoj72sn5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
